### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Testing

### CODE REVIEW

**Comment by PuneetGopinath** [comment]
Example PullRequestEvent with `draft: true`:
```
{
    "id": "16373353417",
    "type": "PullRequestEvent",
    "actor": {
      "id": 76863199,
      "login": "PuneetGopinath",
      "display_login": "PuneetGopinath",
      "gravatar_id": "",
      "url": "https://api.github.com/users/PuneetGopinath",
      "avatar_url": "https://avatars.githubusercontent.com/u/76863199?"
    },
    "repo": {
      "id": 366683174,
      "name": "PuneetGopinath/recent-activity-template",
      "url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template"
    },
    "payload": {
      "action": "opened",
      "number": 1,
      "pull_request": {
        "url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/pulls/1",
        "id": 645174894,
        "node_id": "MDExOlB1bGxSZXF1ZXN0NjQ1MTc0ODk0",
        "html_url": "https://github.com/PuneetGopinath/recent-activity-template/pull/1",
        "diff_url": "https://github.com/PuneetGopinath/recent-activity-template/pull/1.diff",
        "patch_url": "https://github.com/PuneetGopinath/recent-activity-template/pull/1.patch",
        "issue_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/issues/1",
        "number": 1,
        "state": "open",
        "locked": false,
        "title": "Update README.md",
        "user": {
          "login": "PuneetGopinath",
          "id": 76863199,
          "node_id": "MDQ6VXNlcjc2ODYzMTk5",
          "avatar_url": "https://avatars.githubusercontent.com/u/76863199?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/PuneetGopinath",
          "html_url": "https://github.com/PuneetGopinath",
          "followers_url": "https://api.github.com/users/PuneetGopinath/followers",
          "following_url": "https://api.github.com/users/PuneetGopinath/following{/other_user}",
          "gists_url": "https://api.github.com/users/PuneetGopinath/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/PuneetGopinath/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/PuneetGopinath/subscriptions",
          "organizations_url": "https://api.github.com/users/PuneetGopinath/orgs",
          "repos_url": "https://api.github.com/users/PuneetGopinath/repos",
          "events_url": "https://api.github.com/users/PuneetGopinath/events{/privacy}",
          "received_events_url": "https://api.github.com/users/PuneetGopinath/received_events",
          "type": "User",
          "site_admin": false
        },
        "body": "Testing",
        "created_at": "2021-05-15T15:50:37Z",
        "updated_at": "2021-05-15T15:50:37Z",
        "closed_at": null,
        "merged_at": null,
        "merge_commit_sha": null,
        "assignee": null,
        "assignees": [

        ],
        "requested_reviewers": [

        ],
        "requested_teams": [

        ],
        "labels": [

        ],
        "milestone": null,
        "draft": true,
        "commits_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/pulls/1/commits",
        "review_comments_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/pulls/1/comments",
        "review_comment_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/issues/1/comments",
        "statuses_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/statuses/f7e7d3db20fca2f01e75f45f4bbdb3f6f2c6f0a9",
        "head": {
          "label": "PuneetGopinath:test",
          "ref": "test",
          "sha": "f7e7d3db20fca2f01e75f45f4bbdb3f6f2c6f0a9",
          "user": {
            "login": "PuneetGopinath",
            "id": 76863199,
            "node_id": "MDQ6VXNlcjc2ODYzMTk5",
            "avatar_url": "https://avatars.githubusercontent.com/u/76863199?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/PuneetGopinath",
            "html_url": "https://github.com/PuneetGopinath",
            "followers_url": "https://api.github.com/users/PuneetGopinath/followers",
            "following_url": "https://api.github.com/users/PuneetGopinath/following{/other_user}",
            "gists_url": "https://api.github.com/users/PuneetGopinath/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/PuneetGopinath/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/PuneetGopinath/subscriptions",
            "organizations_url": "https://api.github.com/users/PuneetGopinath/orgs",
            "repos_url": "https://api.github.com/users/PuneetGopinath/repos",
            "events_url": "https://api.github.com/users/PuneetGopinath/events{/privacy}",
            "received_events_url": "https://api.github.com/users/PuneetGopinath/received_events",
            "type": "User",
            "site_admin": false
          },
          "repo": {
            "id": 366683174,
            "node_id": "MDEwOlJlcG9zaXRvcnkzNjY2ODMxNzQ=",
            "name": "recent-activity-template",
            "full_name": "PuneetGopinath/recent-activity-template",
            "private": false,
            "owner": {
              "login": "PuneetGopinath",
              "id": 76863199,
              "node_id": "MDQ6VXNlcjc2ODYzMTk5",
              "avatar_url": "https://avatars.githubusercontent.com/u/76863199?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/PuneetGopinath",
              "html_url": "https://github.com/PuneetGopinath",
              "followers_url": "https://api.github.com/users/PuneetGopinath/followers",
              "following_url": "https://api.github.com/users/PuneetGopinath/following{/other_user}",
              "gists_url": "https://api.github.com/users/PuneetGopinath/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/PuneetGopinath/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/PuneetGopinath/subscriptions",
              "organizations_url": "https://api.github.com/users/PuneetGopinath/orgs",
              "repos_url": "https://api.github.com/users/PuneetGopinath/repos",
              "events_url": "https://api.github.com/users/PuneetGopinath/events{/privacy}",
              "received_events_url": "https://api.github.com/users/PuneetGopinath/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/PuneetGopinath/recent-activity-template",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template",
            "forks_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/forks",
            "keys_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/teams",
            "hooks_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/hooks",
            "issue_events_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/issues/events{/number}",
            "events_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/events",
            "assignees_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/assignees{/user}",
            "branches_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/branches{/branch}",
            "tags_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/tags",
            "blobs_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/languages",
            "stargazers_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/stargazers",
            "contributors_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/contributors",
            "subscribers_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/subscribers",
            "subscription_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/subscription",
            "commits_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/contents/{+path}",
            "compare_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/merges",
            "archive_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/downloads",
            "issues_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/issues{/number}",
            "pulls_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/labels{/name}",
            "releases_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/releases{/id}",
            "deployments_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/deployments",
            "created_at": "2021-05-12T10:51:53Z",
            "updated_at": "2021-05-15T12:36:09Z",
            "pushed_at": "2021-05-15T15:50:38Z",
            "git_url": "git://github.com/PuneetGopinath/recent-activity-template.git",
            "ssh_url": "git@github.com:PuneetGopinath/recent-activity-template.git",
            "clone_url": "https://github.com/PuneetGopinath/recent-activity-template.git",
            "svn_url": "https://github.com/PuneetGopinath/recent-activity-template",
            "homepage": null,
            "size": 20,
            "stargazers_count": 1,
            "watchers_count": 1,
            "language": null,
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 1,
            "license": {
              "key": "cc0-1.0",
              "name": "Creative Commons Zero v1.0 Universal",
              "spdx_id": "CC0-1.0",
              "url": "https://api.github.com/licenses/cc0-1.0",
              "node_id": "MDc6TGljZW5zZTY="
            },
            "forks": 0,
            "open_issues": 1,
            "watchers": 1,
            "default_branch": "main"
          }
        },
        "base": {
          "label": "PuneetGopinath:main",
          "ref": "main",
          "sha": "e15e84c7701747a8e9833d71b722e2992f51a0ce",
          "user": {
            "login": "PuneetGopinath",
            "id": 76863199,
            "node_id": "MDQ6VXNlcjc2ODYzMTk5",
            "avatar_url": "https://avatars.githubusercontent.com/u/76863199?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/PuneetGopinath",
            "html_url": "https://github.com/PuneetGopinath",
            "followers_url": "https://api.github.com/users/PuneetGopinath/followers",
            "following_url": "https://api.github.com/users/PuneetGopinath/following{/other_user}",
            "gists_url": "https://api.github.com/users/PuneetGopinath/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/PuneetGopinath/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/PuneetGopinath/subscriptions",
            "organizations_url": "https://api.github.com/users/PuneetGopinath/orgs",
            "repos_url": "https://api.github.com/users/PuneetGopinath/repos",
            "events_url": "https://api.github.com/users/PuneetGopinath/events{/privacy}",
            "received_events_url": "https://api.github.com/users/PuneetGopinath/received_events",
            "type": "User",
            "site_admin": false
          },
          "repo": {
            "id": 366683174,
            "node_id": "MDEwOlJlcG9zaXRvcnkzNjY2ODMxNzQ=",
            "name": "recent-activity-template",
            "full_name": "PuneetGopinath/recent-activity-template",
            "private": false,
            "owner": {
              "login": "PuneetGopinath",
              "id": 76863199,
              "node_id": "MDQ6VXNlcjc2ODYzMTk5",
              "avatar_url": "https://avatars.githubusercontent.com/u/76863199?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/PuneetGopinath",
              "html_url": "https://github.com/PuneetGopinath",
              "followers_url": "https://api.github.com/users/PuneetGopinath/followers",
              "following_url": "https://api.github.com/users/PuneetGopinath/following{/other_user}",
              "gists_url": "https://api.github.com/users/PuneetGopinath/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/PuneetGopinath/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/PuneetGopinath/subscriptions",
              "organizations_url": "https://api.github.com/users/PuneetGopinath/orgs",
              "repos_url": "https://api.github.com/users/PuneetGopinath/repos",
              "events_url": "https://api.github.com/users/PuneetGopinath/events{/privacy}",
              "received_events_url": "https://api.github.com/users/PuneetGopinath/received_events",
              "type": "User",
              "site_admin": false
            },
            "html_url": "https://github.com/PuneetGopinath/recent-activity-template",
            "description": null,
            "fork": false,
            "url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template",
            "forks_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/forks",
            "keys_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/teams",
            "hooks_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/hooks",
            "issue_events_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/issues/events{/number}",
            "events_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/events",
            "assignees_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/assignees{/user}",
            "branches_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/branches{/branch}",
            "tags_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/tags",
            "blobs_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/git/blobs{/sha}",
            "git_tags_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/git/tags{/sha}",
            "git_refs_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/git/refs{/sha}",
            "trees_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/git/trees{/sha}",
            "statuses_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/statuses/{sha}",
            "languages_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/languages",
            "stargazers_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/stargazers",
            "contributors_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/contributors",
            "subscribers_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/subscribers",
            "subscription_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/subscription",
            "commits_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/commits{/sha}",
            "git_commits_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/git/commits{/sha}",
            "comments_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/comments{/number}",
            "issue_comment_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/issues/comments{/number}",
            "contents_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/contents/{+path}",
            "compare_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/compare/{base}...{head}",
            "merges_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/merges",
            "archive_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/{archive_format}{/ref}",
            "downloads_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/downloads",
            "issues_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/issues{/number}",
            "pulls_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/pulls{/number}",
            "milestones_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/milestones{/number}",
            "notifications_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/notifications{?since,all,participating}",
            "labels_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/labels{/name}",
            "releases_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/releases{/id}",
            "deployments_url": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/deployments",
            "created_at": "2021-05-12T10:51:53Z",
            "updated_at": "2021-05-15T12:36:09Z",
            "pushed_at": "2021-05-15T15:50:38Z",
            "git_url": "git://github.com/PuneetGopinath/recent-activity-template.git",
            "ssh_url": "git@github.com:PuneetGopinath/recent-activity-template.git",
            "clone_url": "https://github.com/PuneetGopinath/recent-activity-template.git",
            "svn_url": "https://github.com/PuneetGopinath/recent-activity-template",
            "homepage": null,
            "size": 20,
            "stargazers_count": 1,
            "watchers_count": 1,
            "language": null,
            "has_issues": true,
            "has_projects": true,
            "has_downloads": true,
            "has_wiki": true,
            "has_pages": false,
            "forks_count": 0,
            "mirror_url": null,
            "archived": false,
            "disabled": false,
            "open_issues_count": 1,
            "license": {
              "key": "cc0-1.0",
              "name": "Creative Commons Zero v1.0 Universal",
              "spdx_id": "CC0-1.0",
              "url": "https://api.github.com/licenses/cc0-1.0",
              "node_id": "MDc6TGljZW5zZTY="
            },
            "forks": 0,
            "open_issues": 1,
            "watchers": 1,
            "default_branch": "main"
          }
        },
        "_links": {
          "self": {
            "href": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/pulls/1"
          },
          "html": {
            "href": "https://github.com/PuneetGopinath/recent-activity-template/pull/1"
          },
          "issue": {
            "href": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/issues/1"
          },
          "comments": {
            "href": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/issues/1/comments"
          },
          "review_comments": {
            "href": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/pulls/1/comments"
          },
          "review_comment": {
            "href": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/pulls/comments{/number}"
          },
          "commits": {
            "href": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/pulls/1/commits"
          },
          "statuses": {
            "href": "https://api.github.com/repos/PuneetGopinath/recent-activity-template/statuses/f7e7d3db20fca2f01e75f45f4bbdb3f6f2c6f0a9"
          }
        },
        "author_association": "OWNER",
        "auto_merge": null,
        "active_lock_reason": null,
        "merged": false,
        "mergeable": null,
        "rebaseable": null,
        "mergeable_state": "draft",
        "merged_by": null,
        "comments": 0,
        "review_comments": 0,
        "maintainer_can_modify": false,
        "commits": 1,
        "additions": 1,
        "deletions": 1,
        "changed_files": 1
      }
    },
    "public": true,
    "created_at": "2021-05-15T15:50:38Z"
  }
```

**Comment by abhijoshi2k** [comment]
@PuneetGopinath What is the updated return value now?

**Comment by PuneetGopinath** [comment]
Results of test:

It doesn't trigger a new event for changing draft pr to ready for review pr. I even checked whether the draft param changes to false afterwards, but that too doesn't happen.

**Comment by PuneetGopinath** [comment]
> @PuneetGopinath What is the updated return value now?

Same draft: true

**Comment by abhijoshi2k** [comment]
> > @PuneetGopinath What is the updated return value now?
> 
> Same draft: true

So that means new event is not fired. Let's check for draft PR too in next version

**Comment by PuneetGopinath** [comment]
Yes it means new event is not fired.
I didn't understand why you are saying let's check for draft pr too in next version.
What is next version? Recent Activity's next version?

**Comment by abhijoshi2k** [comment]
> Yes it means new event is not fired.
> I didn't understand why you are saying let's check for draft pr too in next version.
> What is next version? Recent Activity's next version?

Yes recent activity's next version. Whenever we get PR event, and if we get `payload.action: "opened"`, we will also check if it is a draft PR

**Comment by PuneetGopinath** [comment]
Ok👍

**Pull request merged**
